spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/tribu_dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=tribu_user
spring.datasource.password=tribu_pass

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCEhISE=
jwt.expiration=86400000
